### PR TITLE
Fido SWAVES Client

### PR DESCRIPTION
**Pull request by samaloney**
- [x] Demo
- [x] Docs
- [x] Tests
- [x] Handle frequency queries

```
import radiospectra.net
from sunpy.net import Fido, attrs as a
results = Fido.search(a.Time("2010/10/01", "2010/10/02"),
                                     a.Instrument('SWAVES'))

print(results[1])
Results from 1 Provider:

8 Results from the SWAVESClient:
     Start Time           End Time      Instrument Source Spacecraft Provider  Wavelength [2]
------------------- ------------------- ---------- ------ ---------- -------- ----------------
2010-10-01 00:00:00 2010-10-01 23:59:59     SWAVES STEREO          a     NASA    10.0 .. 160.0
2010-10-02 00:00:00 2010-10-02 23:59:59     SWAVES STEREO          a     NASA    10.0 .. 160.0
2010-10-01 00:00:00 2010-10-01 23:59:59     SWAVES STEREO          a     NASA 125.0 .. 16000.0
2010-10-02 00:00:00 2010-10-02 23:59:59     SWAVES STEREO          a     NASA 125.0 .. 16000.0
2010-10-01 00:00:00 2010-10-01 23:59:59     SWAVES STEREO          b     NASA    10.0 .. 160.0
2010-10-02 00:00:00 2010-10-02 23:59:59     SWAVES STEREO          b     NASA    10.0 .. 160.0
2010-10-01 00:00:00 2010-10-01 23:59:59     SWAVES STEREO          b     NASA 125.0 .. 16000.0
2010-10-02 00:00:00 2010-10-02 23:59:59     SWAVES STEREO          b     NASA 125.0 .. 16000.0
```

### CODE REVIEW

**Comment by nabobalis** [comment]
If you have some time, if you could rebase this on top current master.

**Comment by samaloney** [comment]
Yea I'll have a look at these and #34 this week

**Comment by hayesla** [comment]
like the other PR I think these need to be updated to the redesigned generic Fido client format

**Comment by samaloney** [comment]
Yea I know, I'm not sure better to finish these up on the older version of generic client and then update do both at the same time.

**Comment by nabobalis** [comment]
Rebase this and I think we could probably ship this too.

**Comment by samaloney** [comment]
So something isn't quite right here no clue why VSO is returning 24 results from the 09/30 and 10/2 and this is returning 8
I would expect 4 for a single day query 1 lfr, 1hfr x 2 spacecraft.
```
atr = a.Time('2010/10/01', '2010/10/02 00:00')
res = Fido.search(atr, a.Instrument('swaves'))
res
<sunpy.net.fido_factory.UnifiedResponse object at 0x11196b400>
Results from 2 Providers:

24 Results from the VSOClient:
       Start Time               End Time         Source  Instrument Wavelength [2]    Info   Provider   Size  Wavetype
                                                                         MHz                           Mibyte
----------------------- ----------------------- -------- ---------- -------------- --------- -------- ------- --------
2010-09-30 00:00:00.000 2010-10-01 00:00:00.000 STEREO_A     SWAVES  0.125 .. 16.0 HFR ;  ;       SSC 3.51668    BROAD
2010-09-30 00:00:00.000 2010-10-01 00:00:00.000 STEREO_A     SWAVES   0.01 .. 0.16 LFR ;  ;       SSC 0.53499    BROAD
2010-09-30 00:00:00.000 2010-10-01 00:00:00.000 STEREO_B     SWAVES  0.125 .. 16.0 HFR ;  ;       SSC 3.51668    BROAD
2010-09-30 00:00:00.000 2010-10-01 00:00:00.000 STEREO_B     SWAVES   0.01 .. 0.16 LFR ;  ;       SSC 0.53499    BROAD
2010-09-30 00:00:00.000 2010-10-01 00:00:00.000 STEREO_A     SWAVES  0.125 .. 16.0 HFR ;  ;       SSC 3.51668    BROAD
2010-09-30 00:00:00.000 2010-10-01 00:00:00.000 STEREO_A     SWAVES   0.01 .. 0.16 LFR ;  ;       SSC 0.53499    BROAD
                    ...                     ...      ...        ...            ...       ...      ...     ...      ...
2010-10-02 00:00:00.000 2010-10-03 00:00:00.000 STEREO_A     SWAVES   0.01 .. 0.16 LFR ;  ;       SSC 0.53499    BROAD
2010-10-02 00:00:00.000 2010-10-03 00:00:00.000 STEREO_B     SWAVES   0.01 .. 0.16 LFR ;  ;       SSC 0.53499    BROAD
2010-10-02 00:00:00.000 2010-10-03 00:00:00.000 STEREO_A     SWAVES  0.125 .. 16.0 HFR ;  ;       SSC 3.51668    BROAD
2010-10-02 00:00:00.000 2010-10-03 00:00:00.000 STEREO_A     SWAVES   0.01 .. 0.16 LFR ;  ;       SSC 0.53499    BROAD
2010-10-02 00:00:00.000 2010-10-03 00:00:00.000 STEREO_B     SWAVES  0.125 .. 16.0 HFR ;  ;       SSC 3.51668    BROAD
2010-10-02 00:00:00.000 2010-10-03 00:00:00.000 STEREO_B     SWAVES   0.01 .. 0.16 LFR ;  ;       SSC 0.53499    BROAD
Length = 24 rows

8 Results from the SWAVESClient:
       Start Time               End Time        Instrument Source Spacecraft Provider  Wavelength [2]
                                                                                            kHz
----------------------- ----------------------- ---------- ------ ---------- -------- ----------------
2010-10-01 00:00:00.000 2010-10-01 23:59:59.999     SWAVES STEREO          a     NASA    10.0 .. 160.0
2010-10-02 00:00:00.000 2010-10-02 23:59:59.999     SWAVES STEREO          a     NASA    10.0 .. 160.0
2010-10-01 00:00:00.000 2010-10-01 23:59:59.999     SWAVES STEREO          a     NASA 125.0 .. 16000.0
2010-10-02 00:00:00.000 2010-10-02 23:59:59.999     SWAVES STEREO          a     NASA 125.0 .. 16000.0
2010-10-01 00:00:00.000 2010-10-01 23:59:59.999     SWAVES STEREO          b     NASA    10.0 .. 160.0
2010-10-02 00:00:00.000 2010-10-02 23:59:59.999     SWAVES STEREO          b     NASA    10.0 .. 160.0
2010-10-01 00:00:00.000 2010-10-01 23:59:59.999     SWAVES STEREO          b     NASA 125.0 .. 16000.0
2010-10-02 00:00:00.000 2010-10-02 23:59:59.999     SWAVES STEREO          b     NASA 125.0 .. 16000.0
```

**Comment by nabobalis** [comment]
What is the difference between this client and the VSO?

**Comment by samaloney** [comment]
Well the VSO didn't provide swaves data when I started this 🙈 but other than that not sure, I guess the data source? And the VSO seems to have a different interpretation of start and end times returning too many results which I guess is better than too few 😆 

```python
atr = a.Time('2010/10/01', '2010/10/01')
res = Fido.search(atr, a.Instrument('swaves'))

res
<sunpy.net.fido_factory.UnifiedResponse object at 0x11f1b5eb8>
Results from 2 Providers:

16 Results from the VSOClient:
       Start Time               End Time         Source  Instrument Wavelength [2]    Info   Provider   Size  Wavetype
                                                                         MHz                           Mibyte
----------------------- ----------------------- -------- ---------- -------------- --------- -------- ------- --------
2010-09-30 00:00:00.000 2010-10-01 00:00:00.000 STEREO_A     SWAVES  0.125 .. 16.0 HFR ;  ;       SSC 3.51668    BROAD
2010-09-30 00:00:00.000 2010-10-01 00:00:00.000 STEREO_A     SWAVES   0.01 .. 0.16 LFR ;  ;       SSC 0.53499    BROAD
2010-09-30 00:00:00.000 2010-10-01 00:00:00.000 STEREO_B     SWAVES  0.125 .. 16.0 HFR ;  ;       SSC 3.51668    BROAD
2010-09-30 00:00:00.000 2010-10-01 00:00:00.000 STEREO_B     SWAVES   0.01 .. 0.16 LFR ;  ;       SSC 0.53499    BROAD
2010-09-30 00:00:00.000 2010-10-01 00:00:00.000 STEREO_A     SWAVES  0.125 .. 16.0 HFR ;  ;       SSC 3.51668    BROAD
2010-09-30 00:00:00.000 2010-10-01 00:00:00.000 STEREO_A     SWAVES   0.01 .. 0.16 LFR ;  ;       SSC 0.53499    BROAD
                    ...                     ...      ...        ...            ...       ...      ...     ...      ...
2010-10-01 00:00:00.000 2010-10-02 00:00:00.000 STEREO_A     SWAVES   0.01 .. 0.16 LFR ;  ;       SSC 0.53499    BROAD
2010-10-01 00:00:00.000 2010-10-02 00:00:00.000 STEREO_B     SWAVES   0.01 .. 0.16 LFR ;  ;       SSC 0.53499    BROAD
2010-10-01 00:00:00.000 2010-10-02 00:00:00.000 STEREO_A     SWAVES  0.125 .. 16.0 HFR ;  ;       SSC 3.51668    BROAD
2010-10-01 00:00:00.000 2010-10-02 00:00:00.000 STEREO_A     SWAVES   0.01 .. 0.16 LFR ;  ;       SSC 0.53499    BROAD
2010-10-01 00:00:00.000 2010-10-02 00:00:00.000 STEREO_B     SWAVES  0.125 .. 16.0 HFR ;  ;       SSC 3.51668    BROAD
2010-10-01 00:00:00.000 2010-10-02 00:00:00.000 STEREO_B     SWAVES   0.01 .. 0.16 LFR ;  ;       SSC 0.53499    BROAD
Length = 16 rows

4 Results from the SWAVESClient:
       Start Time               End Time        Instrument Source Spacecraft Provider  Wavelength [2]
                                                                                            kHz
----------------------- ----------------------- ---------- ------ ---------- -------- ----------------
2010-10-01 00:00:00.000 2010-10-01 23:59:59.999     SWAVES STEREO          a     NASA    10.0 .. 160.0
2010-10-01 00:00:00.000 2010-10-01 23:59:59.999     SWAVES STEREO          a     NASA 125.0 .. 16000.0
2010-10-01 00:00:00.000 2010-10-01 23:59:59.999     SWAVES STEREO          b     NASA    10.0 .. 160.0
2010-10-01 00:00:00.000 2010-10-01 23:59:59.999     SWAVES STEREO          b     NASA 125.0 .. 16000.0
```

**Comment by nabobalis** [comment]
I guess I am asking if the VSO client is enough and if there are some odd things with the results we should ask them to check for us.

**Comment by samaloney** [comment]
Well this client use the same source as the PSP client so I think, also I think it's better to have more data sources than less. We should ask someone in VSO why the return extra days of data though.

**Comment by nabobalis** [comment]
I would rather follow the policy as sunpy master does. If the VSO serves the data, we should have a good reason to have a separate client.

**Comment by samaloney** [comment]
More than this client returns the correct results and will do so as long as https://solar-radio.gsfc.nasa.gov/data/ is live?

**Comment by samaloney** [comment]
So the files are downloaded from different places (https://solar-radio.gsfc.nasa.gov/data/ v https://stereo-ssc.nascom.nasa.gov/data/ins_data/swaves/) and are also different too or at least the shasum of two files with the same names are different.

**Comment by nabobalis** [comment]
Do we know what the the difference is?

**Review by nabobalis — APPROVED** [review]

**Comment by nabobalis** [comment]
We should open an issue to figure out the differences.

**Pull request merged**
